---
- name: Rancher Kubernetes Nodes
  hosts: rancher_kubernetes_nodes
  pre_tasks:
  - name: Add universe repository for bionic
    apt_repository: 
      repo: deb http://archive.ubuntu.com/ubuntu bionic universe
      state: present
    when: ansible_distribution_release == 'bionic'
  roles:
    - rkeserver.common
    - geerlingguy.firewall
    - geerlingguy.docker
    - singleplatform-eng.users
